# Development Profile
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb_dev

# Security (Relaxed for development)
cookie.secure=false
cookie.same-site=Lax

# Logging
logging.level.com.dvein.banking_backend=DEBUG

# Email (Console for development)
spring.mail.host=localhost
spring.mail.port=1025