# Production Profile
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Database
spring.datasource.url=jdbc:postgresql://prod-db-host:5432/bankdb_prod

# Security (Strict for production)
cookie.secure=true
cookie.same-site=Strict

# Logging
logging.level.com.dvein.banking_backend=WARN